marcuspezzaioli/Models/ErrorViewModel.cs
namespace marcuspezzaioli.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

marcuspezzaioli/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;

namespace marcuspezzaioli.Controllers
{
	public class AboutMeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

marcuspezzaioli/Controllers/HomeController.cs
using marcuspezzaioli.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace marcuspezzaioli.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

marcuspezzaioli/Views/AboutMe/Index.cshtml
@{
}

<div class="mt-3 row align-items-center">

	<div class="col-md-1 offset-md-1 circular-image border">
		<img src="https://live.staticflickr.com/65535/53278320080_11f1ff3224_q.jpg" alt="Headshot of Marcus Pezzaioli" />
	</div>

	<div class="col-6 col-md text-center">
		<h1 class="">About Me</h1>
	</div>

	<div class="col-md-1 offset-md-1 d-none d-md-block">
	</div>
</div>

<div class="col-8 offset-2 mt-3">
	<div class="jade-green-line"></div>
</div>

<div class="row mt-3 mt-md-5">
	<div class="col-10 col-md-4 offset-1">
		<p>
			Hi, <br /> <br />
			Welcome to my personal space, developed using ASP.NET Core MVC.
			With 5 years of experience crafting mathematical models, I ventured into building this site to explore the diverse capabilities of C#.<br /> <br />

			Feel free to look at the code <a href="https://github.com/marcuspezzaioli/PersonalSite" target="_blank" rel="noopener noreferrer">here</a>. <br /> <br />

			As my journey in development progresses, I'll keep updating this site with my latest projects and endeavors.  <br /> <br />

			If you're interested in discussing anything – especially around C#, Go, or VB.NET – don't hesitate to reach out through the links on this page.
		</p>
	</div>

	<div class="col-8 offset-2 mt-3 d-block d-md-none">
		<div class="jade-green-line"></div>
	</div>


	<div class="col-10 col-md-4 offset-1 mt-3 mt-md-0">
		<h4 class="mb-3 mb-md-5">Contact me via:</h4>
		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin me-3" viewBox="0 0 16 16">
			<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
		</svg>
		<a href="https://www.linkedin.com/in/marcuspezzaioli/" target="_blank" rel="noopener noreferrer">My linked in profile.</a>
		<br />
		<br />
		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x me-3" viewBox="0 0 16 16">
			<path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865l8.875 11.633Z" />
		</svg>
		<a href="https://twitter.com/marcuspezz" target="_blank" rel="noopener noreferrer">My X (formally Twitter) profile.</a>
		<br />
		<br />
		<p>Alternatively, email me at marcuspezzaioli[at]gmail[dot]com</p>
	</div>



</div>

marcuspezzaioli/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}


<section class="home-layout">


	<header class="page-title-container">
		<h1 class="page-title">
			Hi, my name is <br />
			<strong>Marcus Pezzaioli</strong>.
		</h1>
	</header>


	<div class="blurb-container">
		<p class="blurb">
			I build things with C#, VB.Net and Go.
		</p>
	</div>



	<div class="button-container">
		<a class="btn btn-jade" asp-area="" asp-controller="AboutMe" asp-action="Index">Find Out More</a>
	</div>



@*	<div class="hero-img">
		<img class="feature-img" src="https://live.staticflickr.com/65535/53274526951_81ec332668_b.jpg" alt="An AI generated monitor with jade green and white code on a black background." class="img-fluid">
	</div>*@
</section>

marcuspezzaioli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - marcuspezzaioli</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/marcuspezzaioli.styles.css" asp-append-version="true" />
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
	@{
		string controllerForWhichNavIsBlocked = "Home";
	}
	

	@if (ViewContext.RouteData.Values["controller"] != null && ViewContext.RouteData.Values["controller"].ToString() != controllerForWhichNavIsBlocked)
	{
		<header>
			<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
				<div class="container-fluid">
					<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marcus Pezzaioli</a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
							aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
						<ul class="navbar-nav flex-grow-1">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</header>
	}

	<div>
			@RenderBody()
	</div>


	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Marcus Pezzaioli
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>